### init-home
GET http://localhost:3001/api/init-home?eventCode=TOKYU_20250517

### init-form
GET http://localhost:3001/api/init-form?eventCode=TOKYU_20250517&latitude=35.4615296&longitude=139.5982336

