import type { Metadata } from "next";
import { Geist, Geist_Mono, DotGothic16 } from "next/font/google";
import "./globals.css";
import { Box, Container } from "@mui/material";
import Header from "@/components/composite/Header";
import { NavigationBar } from "@/components/composite/NavigationBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const dotGothic16 = DotGothic16({
    weight: "400",
    variable: "--font-dot-gothic",
    subsets: ["latin"],
});

// export const metadataとすると、headに展開される
export const metadata: Metadata = {
    title: "東急線リアル桃鉄",
    description: "Generated by create next app",
    icons: {
        icon: "/momotetsu.png",
    },
};

// RootLayoutコンポーネントは、アプリケーション全体のレイアウトを定義します
// 各ページのコンテンツがchildrenに挿入されます
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="ja"
            className={`${geistSans.variable} ${geistMono.variable} ${dotGothic16.variable}`}
            suppressHydrationWarning={true}
        >
            <body className={dotGothic16.className}>
                <Container
                    maxWidth="md"
                    disableGutters
                    sx={{
                        minHeight: "100dvh",
                        display: "flex",
                        flexDirection: "column",
                    }}
                >
                    <Header />
                    <Box sx={{ flex: 1, padding: 1 }}>{children}</Box>
                    <NavigationBar />
                </Container>
            </body>
        </html>
    );
}
