import type { Metadata } from "next";
import { Geist, Geist_Mono, DotGothic16 } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import ThemeRegistry from "@/components/ThemeRegistry";
import { UserIconProvider } from "@/contexts/UserIconContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const dotGothic16 = DotGothic16({
    weight: "400",
    variable: "--font-dot-gothic",
    subsets: ["latin"],
});

// export const metadataとすると、headに展開される
export const metadata: Metadata = {
    title: "リアル桃鉄",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/icon-192x192.png", sizes: "192x192", type: "image/png" },
            { url: "/icon-512x512.png", sizes: "512x512", type: "image/png" },
        ],
        apple: [
            { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
            { url: "/icon-192x192.png", sizes: "192x192", type: "image/png" },
        ],
    },
    viewport: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover", // iOSのSafeArea対応
};

/**
 * アプリケーションのルートレイアウト
 * @param {Readonly<{ children: React.ReactNode }>} props - コンポーネントのプロパティ
 * @returns {JSX.Element} - アプリケーションのルートレイアウト
 */
const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>): React.JSX.Element => {
    return (
        <html
            lang="ja"
            className={`${geistSans.variable} ${geistMono.variable} ${dotGothic16.variable}`}
            suppressHydrationWarning={true}
        >
            <head>
                <meta name="emotion-insertion-point" content="" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
            </head>
            <body className={dotGothic16.className} suppressHydrationWarning={true}>
                <ThemeRegistry>
                    <UserIconProvider>
                        <Container
                            maxWidth="md"
                            disableGutters
                            sx={{
                                minHeight: "100dvh",
                                display: "flex",
                                flexDirection: "column",
                            }}
                        >
                            {children}
                        </Container>
                    </UserIconProvider>
                </ThemeRegistry>
            </body>
        </html>
    );
};

export default RootLayout;
